package Menu;


public class Empleados extends javax.swing.JFrame {

    
    private void cargarEmpleadosDesdeBD() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) InformacionEmpleados.getModel();
    model.setRowCount(0); // Limpia la tabla

    String sql = "SELECT dni, nombres_apellidos, celular, correo, numero_cuenta, banco, contrasena, cargo FROM empleados";

    try (java.sql.Connection con = Conexion.conectar();
         java.sql.Statement st = con.createStatement();
         java.sql.ResultSet rs = st.executeQuery(sql)) {

        while (rs.next()) {
            String dni = rs.getString("dni");
            String nombre = rs.getString("nombres_apellidos");
            String celular = rs.getString("celular");
            String correo = rs.getString("correo");
            String numeroCuenta = rs.getString("numero_cuenta");
            String banco = rs.getString("banco");
            String contrasena = rs.getString("contrasena");
            String cargo = rs.getString("cargo");

            model.addRow(new Object[]{dni, nombre, celular, correo, numeroCuenta, banco, contrasena, cargo});
        }

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar los empleados: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    private String dniUsuario;
    private String contrasenaUsuario;
    
    public Empleados(String dniUsuario, String contrasenaUsuario) {
        initComponents();
        this.dniUsuario = dniUsuario;
        this.contrasenaUsuario = contrasenaUsuario;
        setLocationRelativeTo(null);
        if (!(dniUsuario.equals("75284260") && contrasenaUsuario.equals("Overw@tch73"))) {
            EmpleadosVentana.setVisible(false);
        }
    
    
        
    // Inicializar los placeholders en cada JTextField
        
        agregarPlaceholder(DNITF, "DNI");
        agregarPlaceholder(NombreTF, "Nombre");
        agregarPlaceholder(CelularTF, "Celular");
        agregarPlaceholder(CorreoTF, "Correo");
        agregarPlaceholder(NumeroDeCuenta, "Número de Cuenta");
        agregarPlaceholder(BancoTF, "Banco");
        agregarPlaceholder(ContraseñaTF, "Contraseña");
        agregarPlaceholder(CargoTF, "Cargo");


    // Configurar tabla vacía con encabezados
    
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[]{"DNI", "Nombre", "Celular", "Correo", "Número de Cuenta", "Banco", "Contraseña", "Cargo"}, 0
        );
        InformacionEmpleados.setModel(model);
        
        cargarEmpleadosDesdeBD();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IngresoVentana = new javax.swing.JButton();
        SalidaVentana = new javax.swing.JButton();
        HistorialVentana = new javax.swing.JButton();
        EspaciosVentana = new javax.swing.JButton();
        EmpleadosVentana = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CargoTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        IngresoVentana1 = new javax.swing.JButton();
        SalidaVentana1 = new javax.swing.JButton();
        HistorialVentana1 = new javax.swing.JButton();
        EspaciosVentana1 = new javax.swing.JButton();
        EmpleadosVentana1 = new javax.swing.JButton();
        Agregar = new javax.swing.JToggleButton();
        Editar = new javax.swing.JToggleButton();
        Eliminar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InformacionEmpleados = new javax.swing.JTable();
        Seleccionar = new javax.swing.JButton();
        NombreTF = new javax.swing.JTextField();
        DNITF = new javax.swing.JTextField();
        CelularTF = new javax.swing.JTextField();
        CorreoTF = new javax.swing.JTextField();
        NumeroDeCuenta = new javax.swing.JTextField();
        BancoTF = new javax.swing.JTextField();
        ContraseñaTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        IngresoVentana.setBackground(new java.awt.Color(248, 243, 238));
        IngresoVentana.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        IngresoVentana.setForeground(new java.awt.Color(97, 133, 184));
        IngresoVentana.setText("    Ingreso");
        IngresoVentana.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        IngresoVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresoVentana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IngresoVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoVentanaActionPerformed(evt);
            }
        });

        SalidaVentana.setBackground(new java.awt.Color(248, 243, 238));
        SalidaVentana.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        SalidaVentana.setForeground(new java.awt.Color(97, 133, 184));
        SalidaVentana.setText("    Salida");
        SalidaVentana.setBorder(null);
        SalidaVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalidaVentana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SalidaVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaVentanaActionPerformed(evt);
            }
        });

        HistorialVentana.setBackground(new java.awt.Color(248, 243, 238));
        HistorialVentana.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        HistorialVentana.setForeground(new java.awt.Color(97, 133, 184));
        HistorialVentana.setText("    Historial");
        HistorialVentana.setBorder(null);
        HistorialVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistorialVentana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HistorialVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialVentanaActionPerformed(evt);
            }
        });

        EspaciosVentana.setBackground(new java.awt.Color(248, 243, 238));
        EspaciosVentana.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        EspaciosVentana.setForeground(new java.awt.Color(97, 133, 184));
        EspaciosVentana.setText("    Espacios");
        EspaciosVentana.setBorder(null);
        EspaciosVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EspaciosVentana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EspaciosVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspaciosVentanaActionPerformed(evt);
            }
        });

        EmpleadosVentana.setBackground(new java.awt.Color(248, 243, 238));
        EmpleadosVentana.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        EmpleadosVentana.setForeground(new java.awt.Color(97, 133, 184));
        EmpleadosVentana.setText("    Empleados");
        EmpleadosVentana.setBorder(null);
        EmpleadosVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpleadosVentana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmpleadosVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosVentanaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargoTF.setForeground(new java.awt.Color(204, 204, 204));
        CargoTF.setText("Cargo");
        CargoTF.setBorder(null);
        CargoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoTFActionPerformed(evt);
            }
        });
        jPanel3.add(CargoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 340, 30));

        jPanel4.setBackground(new java.awt.Color(248, 243, 238));

        IngresoVentana1.setBackground(new java.awt.Color(248, 243, 238));
        IngresoVentana1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        IngresoVentana1.setForeground(new java.awt.Color(97, 133, 184));
        IngresoVentana1.setText("    Ingreso");
        IngresoVentana1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        IngresoVentana1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresoVentana1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IngresoVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoVentana1ActionPerformed(evt);
            }
        });

        SalidaVentana1.setBackground(new java.awt.Color(248, 243, 238));
        SalidaVentana1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        SalidaVentana1.setForeground(new java.awt.Color(97, 133, 184));
        SalidaVentana1.setText("    Salida");
        SalidaVentana1.setBorder(null);
        SalidaVentana1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalidaVentana1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SalidaVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaVentana1ActionPerformed(evt);
            }
        });

        HistorialVentana1.setBackground(new java.awt.Color(248, 243, 238));
        HistorialVentana1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        HistorialVentana1.setForeground(new java.awt.Color(97, 133, 184));
        HistorialVentana1.setText("    Historial");
        HistorialVentana1.setBorder(null);
        HistorialVentana1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistorialVentana1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HistorialVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialVentana1ActionPerformed(evt);
            }
        });

        EspaciosVentana1.setBackground(new java.awt.Color(248, 243, 238));
        EspaciosVentana1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        EspaciosVentana1.setForeground(new java.awt.Color(97, 133, 184));
        EspaciosVentana1.setText("    Espacios");
        EspaciosVentana1.setBorder(null);
        EspaciosVentana1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EspaciosVentana1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EspaciosVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspaciosVentana1ActionPerformed(evt);
            }
        });

        EmpleadosVentana1.setBackground(new java.awt.Color(248, 243, 238));
        EmpleadosVentana1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        EmpleadosVentana1.setForeground(new java.awt.Color(97, 133, 184));
        EmpleadosVentana1.setText("    Empleados");
        EmpleadosVentana1.setBorder(null);
        EmpleadosVentana1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmpleadosVentana1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmpleadosVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosVentana1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(IngresoVentana1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HistorialVentana1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(SalidaVentana1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(EmpleadosVentana1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(EspaciosVentana1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(IngresoVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SalidaVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(HistorialVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspaciosVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpleadosVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 650));

        Agregar.setBackground(new java.awt.Color(51, 204, 0));
        Agregar.setFont(new java.awt.Font("Roboto ExtraBold", 1, 12)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel3.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, 30));

        Editar.setBackground(new java.awt.Color(255, 204, 0));
        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPanel3.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, 30));

        Eliminar.setBackground(new java.awt.Color(255, 51, 51));
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel3.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, 30));

        InformacionEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Celular", "Correo", "Numero de cuenta", "Banco", "Contraseña", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(InformacionEmpleados);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 880, 160));

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPanel3.add(Seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, 30));

        NombreTF.setForeground(new java.awt.Color(204, 204, 204));
        NombreTF.setText("Nombre");
        NombreTF.setBorder(null);
        NombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTFActionPerformed(evt);
            }
        });
        jPanel3.add(NombreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 340, 30));

        DNITF.setForeground(new java.awt.Color(204, 204, 204));
        DNITF.setText("DNI");
        DNITF.setBorder(null);
        DNITF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNITFActionPerformed(evt);
            }
        });
        jPanel3.add(DNITF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 340, 30));

        CelularTF.setForeground(new java.awt.Color(204, 204, 204));
        CelularTF.setText("Celular");
        CelularTF.setBorder(null);
        CelularTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelularTFActionPerformed(evt);
            }
        });
        jPanel3.add(CelularTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 340, 30));

        CorreoTF.setForeground(new java.awt.Color(204, 204, 204));
        CorreoTF.setText("Correo");
        CorreoTF.setBorder(null);
        CorreoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoTFActionPerformed(evt);
            }
        });
        jPanel3.add(CorreoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 340, 30));

        NumeroDeCuenta.setForeground(new java.awt.Color(204, 204, 204));
        NumeroDeCuenta.setText("Numero de Cuenta");
        NumeroDeCuenta.setBorder(null);
        NumeroDeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroDeCuentaActionPerformed(evt);
            }
        });
        jPanel3.add(NumeroDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 340, 30));

        BancoTF.setForeground(new java.awt.Color(204, 204, 204));
        BancoTF.setText("Banco");
        BancoTF.setBorder(null);
        BancoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BancoTFActionPerformed(evt);
            }
        });
        jPanel3.add(BancoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 340, 30));

        ContraseñaTF.setForeground(new java.awt.Color(204, 204, 204));
        ContraseñaTF.setText("Contraseña");
        ContraseñaTF.setBorder(null);
        ContraseñaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTFActionPerformed(evt);
            }
        });
        jPanel3.add(ContraseñaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 340, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 340, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 340, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 340, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 340, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 340, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 340, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 340, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 340, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CargoTFActionPerformed

    private void NombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTFActionPerformed

    private void DNITFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNITFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNITFActionPerformed

    private void CelularTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelularTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelularTFActionPerformed

    private void CorreoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoTFActionPerformed

    private void NumeroDeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroDeCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroDeCuentaActionPerformed

    private void BancoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BancoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BancoTFActionPerformed

    private void ContraseñaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTFActionPerformed

    private void IngresoVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoVentanaActionPerformed
        // TODO add your handling code here:
        Ingreso newframe = new Ingreso(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IngresoVentanaActionPerformed

    private void SalidaVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaVentanaActionPerformed
        // TODO add your handling code here:
        Salida newframe = new Salida(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalidaVentanaActionPerformed

    private void HistorialVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialVentanaActionPerformed
        // TODO add your handling code here:
        Historial newframe = new Historial(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HistorialVentanaActionPerformed

    private void EspaciosVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaciosVentanaActionPerformed
        // TODO add your handling code here:
        Espacios newframe = new Espacios(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EspaciosVentanaActionPerformed

    private void EmpleadosVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosVentanaActionPerformed
        // TODO add your handling code here:
        Empleados newframe = new Empleados(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmpleadosVentanaActionPerformed

    private void IngresoVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoVentana1ActionPerformed
        // TODO add your handling code here:
        Ingreso newframe = new Ingreso(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IngresoVentana1ActionPerformed

    private void SalidaVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaVentana1ActionPerformed
        // TODO add your handling code here:
        Salida newframe = new Salida(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalidaVentana1ActionPerformed

    private void HistorialVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialVentana1ActionPerformed
        // TODO add your handling code here:
        Historial newframe = new Historial(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HistorialVentana1ActionPerformed

    private void EspaciosVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaciosVentana1ActionPerformed
        // TODO add your handling code here:
        Espacios newframe = new Espacios(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EspaciosVentana1ActionPerformed

    private void EmpleadosVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosVentana1ActionPerformed
        // TODO add your handling code here:
        Empleados newframe = new Empleados(dniUsuario, contrasenaUsuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmpleadosVentana1ActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        // TODO add your handling code here:
        int fila = InformacionEmpleados.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor selecciona una fila.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) InformacionEmpleados.getModel();

    DNITF.setText(model.getValueAt(fila, 0).toString());
    NombreTF.setText(model.getValueAt(fila, 1).toString());
    CelularTF.setText(model.getValueAt(fila, 2).toString());
    CorreoTF.setText(model.getValueAt(fila, 3).toString());
    NumeroDeCuenta.setText(model.getValueAt(fila, 4).toString());
    BancoTF.setText(model.getValueAt(fila, 5).toString());
    ContraseñaTF.setText(model.getValueAt(fila, 6).toString());
    CargoTF.setText(model.getValueAt(fila, 7).toString());

    DNITF.setEditable(false); // No se debe cambiar el DNI porque es clave primaria
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        
        
        String dni = DNITF.getText().trim();
        String nombre = NombreTF.getText().trim();
        String celular = CelularTF.getText().trim();
        String correo = CorreoTF.getText().trim();
        String numeroCuenta = NumeroDeCuenta.getText().trim();
        String banco = BancoTF.getText().trim();
        String contrasena = ContraseñaTF.getText().trim();
        String cargo = CargoTF.getText().trim();

    // 1️⃣ Validar que no haya campos vacíos
    if (dni.isEmpty() || nombre.isEmpty() || celular.isEmpty() || correo.isEmpty() ||
        numeroCuenta.isEmpty() || banco.isEmpty() || contrasena.isEmpty() || cargo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 2️⃣ Validaciones específicas
    if (!dni.matches("\\d{8}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El DNI debe tener exactamente 8 dígitos numéricos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!nombre.matches("^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras y espacios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!celular.matches("\\d{9}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El número de celular debe tener exactamente 9 dígitos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!correo.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El correo electrónico no tiene un formato válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!numeroCuenta.matches("\\d{20}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El número de cuenta debe tener exactamente 20 dígitos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!contrasena.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&#%'?¡¿])[A-Za-z\\d@$!%*?&]{8,}$")) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "La contraseña debe tener al menos 8 caracteres, incluir una mayúscula, una minúscula, un número y un carácter especial.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3️⃣ Insertar en base de datos
    String sql = "INSERT INTO empleados (dni, nombres_apellidos, celular, correo, numero_cuenta, banco, contrasena, cargo) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    try (java.sql.Connection con = Conexion.conectar();
         java.sql.PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, dni);
        ps.setString(2, nombre);
        ps.setString(3, celular);
        ps.setString(4, correo);
        ps.setString(5, numeroCuenta);
        ps.setString(6, banco);
        ps.setString(7, contrasena);
        ps.setString(8, cargo);

        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Empleado agregado correctamente.");

        // 4️⃣ Agregar fila a la tabla
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) InformacionEmpleados.getModel();
        model.addRow(new Object[]{dni, nombre, celular, correo, numeroCuenta, banco, contrasena, cargo});

        // 5️⃣ Limpiar campos
        DNITF.setText("");
        NombreTF.setText("");
        CelularTF.setText("");
        CorreoTF.setText("");
        NumeroDeCuenta.setText("");
        BancoTF.setText("");
        ContraseñaTF.setText("");
        CargoTF.setText("");

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al agregar empleado: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AgregarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        int fila = InformacionEmpleados.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un empleado para editar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String dni = DNITF.getText().trim();
        String nombre = NombreTF.getText().trim();
        String celular = CelularTF.getText().trim();
        String correo = CorreoTF.getText().trim();
        String numeroCuenta = NumeroDeCuenta.getText().trim();
        String banco = BancoTF.getText().trim();
        String contrasena = ContraseñaTF.getText().trim();
        String cargo = CargoTF.getText().trim();

        // ✅ Validaciones rápidas
        if (dni.isEmpty() || nombre.isEmpty() || celular.isEmpty() || correo.isEmpty() ||
            numeroCuenta.isEmpty() || banco.isEmpty() || contrasena.isEmpty() || cargo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 2️⃣ Validaciones específicas
        if (!dni.matches("\\d{8}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El DNI debe tener exactamente 8 dígitos numéricos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!nombre.matches("^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras y espacios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!celular.matches("\\d{9}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El número de celular debe tener exactamente 9 dígitos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!correo.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El correo electrónico no tiene un formato válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!numeroCuenta.matches("\\d{20}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El número de cuenta debe tener exactamente 20 dígitos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!contrasena.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La contraseña debe tener al menos 8 caracteres, incluir una mayúscula, una minúscula, un número y un carácter especial.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

    // ✅ Consulta SQL de actualización
    String sql = "UPDATE empleados SET nombres_apellidos=?, celular=?, correo=?, numero_cuenta=?, banco=?, contrasena=?, cargo=? WHERE dni=?";

    try (java.sql.Connection con = Conexion.conectar();
         java.sql.PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, nombre);
        ps.setString(2, celular);
        ps.setString(3, correo);
        ps.setString(4, numeroCuenta);
        ps.setString(5, banco);
        ps.setString(6, contrasena);
        ps.setString(7, cargo);
        ps.setString(8, dni);

        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Empleado actualizado correctamente.");

        // ✅ Actualizar también la tabla visual
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) InformacionEmpleados.getModel();
        model.setValueAt(nombre, fila, 1);
        model.setValueAt(celular, fila, 2);
        model.setValueAt(correo, fila, 3);
        model.setValueAt(numeroCuenta, fila, 4);
        model.setValueAt(banco, fila, 5);
        model.setValueAt(contrasena, fila, 6);
        model.setValueAt(cargo, fila, 7);

        // ✅ Limpiar campos
        DNITF.setText("");
        NombreTF.setText("");
        CelularTF.setText("");
        CorreoTF.setText("");
        NumeroDeCuenta.setText("");
        BancoTF.setText("");
        ContraseñaTF.setText("");
        CargoTF.setText("");
        DNITF.setEditable(true);

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al editar: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = InformacionEmpleados.getSelectedRow();

    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un empleado de la tabla para eliminar.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String dni = InformacionEmpleados.getValueAt(filaSeleccionada, 0).toString();

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de eliminar al empleado con DNI: " + dni + "?", 
            "Confirmar eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    // SQL para eliminar el empleado
    String sql = "DELETE FROM empleados WHERE dni = ?";

    try (java.sql.Connection con = Conexion.conectar();
         java.sql.PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, dni);
        int filasEliminadas = ps.executeUpdate();

        if (filasEliminadas > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");

            // Eliminar la fila de la tabla
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) InformacionEmpleados.getModel();
            model.removeRow(filaSeleccionada);

            // Limpiar campos
            DNITF.setText("");
            NombreTF.setText("");
            CelularTF.setText("");
            CorreoTF.setText("");
            NumeroDeCuenta.setText("");
            BancoTF.setText("");
            ContraseñaTF.setText("");
            CargoTF.setText("");

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el empleado para eliminar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar empleado: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void agregarPlaceholder(javax.swing.JTextField textField, String placeholder) {
    textField.setForeground(java.awt.Color.GRAY);
    textField.setText(placeholder);

    textField.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (textField.getText().equals(placeholder)) {
                textField.setText("");
                textField.setForeground(java.awt.Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (textField.getText().isEmpty()) {
                textField.setForeground(java.awt.Color.GRAY);
                textField.setText(placeholder);
            }
        }
    });
}

    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Agregar;
    private javax.swing.JTextField BancoTF;
    private javax.swing.JTextField CargoTF;
    private javax.swing.JTextField CelularTF;
    private javax.swing.JTextField ContraseñaTF;
    private javax.swing.JTextField CorreoTF;
    private javax.swing.JTextField DNITF;
    private javax.swing.JToggleButton Editar;
    private javax.swing.JToggleButton Eliminar;
    private javax.swing.JButton EmpleadosVentana;
    private javax.swing.JButton EmpleadosVentana1;
    private javax.swing.JButton EspaciosVentana;
    private javax.swing.JButton EspaciosVentana1;
    private javax.swing.JButton HistorialVentana;
    private javax.swing.JButton HistorialVentana1;
    private javax.swing.JTable InformacionEmpleados;
    private javax.swing.JButton IngresoVentana;
    private javax.swing.JButton IngresoVentana1;
    private javax.swing.JTextField NombreTF;
    private javax.swing.JTextField NumeroDeCuenta;
    private javax.swing.JButton SalidaVentana;
    private javax.swing.JButton SalidaVentana1;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
