package Menu;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author NITROX
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        dniTF.setText("Ingrese DNI del Usuario");
        dniTF.setForeground(Color.GRAY);

        contrasenaTF.setText("********");
        contrasenaTF.setForeground(Color.GRAY);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dniTF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        contrasenaTF = new javax.swing.JPasswordField();
        IniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Logotipo Pension Estacionamiento Profesional Azul.png"))); // NOI18N
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jLabel2.setFont(new java.awt.Font("Roboto ExtraBold", 0, 48)); // NOI18N
        jLabel2.setText("Iniciar ");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 150, -1));

        jLabel4.setFont(new java.awt.Font("Roboto ExtraBold", 0, 48)); // NOI18N
        jLabel4.setText("Sesión");
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));
        Fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Logotipo Pension Estacionamiento Profesional Azul.png"))); // NOI18N
        Fondo1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jLabel6.setFont(new java.awt.Font("Roboto ExtraBold", 0, 48)); // NOI18N
        jLabel6.setText("Iniciar ");
        Fondo1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 150, -1));

        jLabel7.setFont(new java.awt.Font("Roboto ExtraBold", 0, 24)); // NOI18N
        jLabel7.setText("Usuario");
        Fondo1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto ExtraBold", 0, 48)); // NOI18N
        jLabel8.setText("Sesión");
        Fondo1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        dniTF.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        dniTF.setForeground(new java.awt.Color(204, 204, 204));
        dniTF.setText("Ingrese DNI de Usuario");
        dniTF.setBorder(null);
        dniTF.setDisabledTextColor(new java.awt.Color(51, 255, 51));
        dniTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dniTFMousePressed(evt);
            }
        });
        dniTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTFActionPerformed(evt);
            }
        });
        Fondo1.add(dniTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 340, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Fondo1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 253, 350, 10));

        jLabel3.setFont(new java.awt.Font("Roboto ExtraBold", 0, 24)); // NOI18N
        jLabel3.setText("Contraseña");
        Fondo1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Fondo1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 350, 10));

        contrasenaTF.setForeground(new java.awt.Color(204, 204, 204));
        contrasenaTF.setText("jPasswordField1");
        contrasenaTF.setBorder(null);
        contrasenaTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenaTFMousePressed(evt);
            }
        });
        Fondo1.add(contrasenaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 350, -1));

        IniciarSesion.setBackground(new java.awt.Color(102, 204, 255));
        IniciarSesion.setFont(new java.awt.Font("Roboto SemiBold", 0, 24)); // NOI18N
        IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesion.setText("Entrar");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });
        Fondo1.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 170, 60));

        Fondo.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTFActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        String dni = dniTF.getText().trim();
        String contrasena = contrasenaTF.getText().trim();

    if (dni.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa el DNI y la contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "SELECT * FROM empleados WHERE dni = ? AND contrasena = ?";

    try (Connection con = Conexion.conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, dni);
        ps.setString(2, contrasena);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso ✅");

            String usuarioDni = dni;
            String usuarioContrasena = contrasena;

            // Crear la ventana de ingreso, pasando el usuario y la contraseña
            Ingreso ventana = new Ingreso(dni, contrasena);
            ventana.setVisible(true);

    this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "DNI o contraseña incorrectos ❌", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al iniciar sesión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void dniTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniTFMousePressed
       // Si el campo DNI tiene el texto por defecto, lo limpia
        if (dniTF.getText().equals("Ingrese DNI de Usuario")) {
            dniTF.setText("");
            dniTF.setForeground(Color.BLACK);
        }

        // Si la contraseña está vacía, vuelve a poner el placeholder
        String password = new String(contrasenaTF.getPassword());
        if (password.isEmpty()) {
            contrasenaTF.setText("********");
            contrasenaTF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_dniTFMousePressed

    private void contrasenaTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaTFMousePressed
        // TODO add your handling code here:
        // Si el campo contraseña tiene el texto por defecto, lo limpia
        String password = new String(contrasenaTF.getPassword());
        if (password.equals("********")) {
            contrasenaTF.setText("");
            contrasenaTF.setForeground(Color.BLACK);
        }

        // Si el campo DNI está vacío, vuelve a poner el placeholder
        if (dniTF.getText().isEmpty()) {
            dniTF.setText("Ingrese DNI de Usuario");
            dniTF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_contrasenaTFMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JPasswordField contrasenaTF;
    private javax.swing.JTextField dniTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
